insert into series (id, title, author_id, subgenre_id) values (null, null, null, null);
insert into series (id, title, author_id, subgenre_id) values (null, null, null, null);
insert into books (id, title, year, series_id) values (null, null, null, null);
insert into books (id, title, year, series_id) values (null, null, null, null);
insert into books (id, title, year, series_id) values (null, null, null, null);
insert into books (id, title, year, series_id) values (null, null, null, null);
insert into books (id, title, year, series_id) values (null, null, null, null);
insert into books (id, title, year, series_id) values (null, null, null, null);
insert into characters (id, name, species, motto, series_id, author_id) values (null, null, null, null, null, null);
insert into characters (id, name, species, motto, series_id, author_id) values (null, null, null, null, null, null);
insert into characters (id, name, species, motto, series_id, author_id) values (null, null, null, null, null, null);
insert into characters (id, name, species, motto, series_id, author_id) values (null, null, null, null, null, null);
insert into characters (id, name, species, motto, series_id, author_id) values (null, null, null, null, null, null);
insert into characters (id, name, species, motto, series_id, author_id) values (null, null, null, null, null, null);
insert into characters (id, name, species, motto, series_id, author_id) values (null, null, null, null, null, null);
insert into characters (id, name, species, motto, series_id, author_id) values (null, null, null, null, null, null);
insert into subgenres (id, name) values (null, null);
insert into subgenres (id, name) values (null, null);
insert into authors (id, name) values (null, null);
insert into authors (id, name) values (null, null);
insert into character_books (id, book_id, character_id) values (null, null, null);
insert into character_books (id, book_id, character_id) values (null, null, null);
insert into character_books (id, book_id, character_id) values (null, null, null);
insert into character_books (id, book_id, character_id) values (null, null, null);
insert into character_books (id, book_id, character_id) values (null, null, null);
insert into character_books (id, book_id, character_id) values (null, null, null);
insert into character_books (id, book_id, character_id) values (null, null, null);
insert into character_books (id, book_id, character_id) values (null, null, null);
insert into character_books (id, book_id, character_id) values (null, null, null);
insert into character_books (id, book_id, character_id) values (null, null, null);
insert into character_books (id, book_id, character_id) values (null, null, null);
insert into character_books (id, book_id, character_id) values (null, null, null);
insert into character_books (id, book_id, character_id) values (null, null, null);
insert into character_books (id, book_id, character_id) values (null, null, null);
insert into character_books (id, book_id, character_id) values (null, null, null);
insert into character_books (id, book_id, character_id) values (null, null, null);
